// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSchoolSystem.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniSchoolSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320235027_InitialPostgresCreate")]
    partial class InitialPostgresCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int?>("CourseSections")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("DbModules");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "C1",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "C2",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "C3",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = "4",
                            ConcurrencyStamp = "C4",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "5",
                            ConcurrencyStamp = "C5",
                            Name = "Parent",
                            NormalizedName = "PARENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "100",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "101",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "102",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "103",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "104",
                            RoleId = "5"
                        },
                        new
                        {
                            UserId = "105",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "106",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseSections")
                        .HasColumnType("integer");

                    b.Property<string>("CourseUserbID")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.Property<int>("TeacherID")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseUserbID");

                    b.HasIndex("TeacherID");

                    b.ToTable("DbCourse");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseModuleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonSection")
                        .HasColumnType("integer");

                    b.Property<int?>("StudentModelId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserDbId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseModuleId");

                    b.HasIndex("StudentModelId");

                    b.HasIndex("UserDbId");

                    b.ToTable("DbLesson");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.LessonContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("DbLessonContent");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.LessonEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EnrolledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("LessonProgress")
                        .HasColumnType("numeric");

                    b.Property<int>("Sections")
                        .HasColumnType("integer");

                    b.Property<string>("StudentId")
                        .HasColumnType("text");

                    b.Property<int?>("StudentName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentName");

                    b.ToTable("DbLessonEnrollments");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.StudentCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("UserDbID")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserDbID");

                    b.ToTable("DbStudentCourses");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.StudentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("StudentEmail")
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .HasColumnType("text");

                    b.Property<string>("StudentName")
                        .HasColumnType("text");

                    b.Property<int>("StudentSection")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("DbStudents");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("DbTeacher");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.TeacherSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("TSection")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherSection");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.UserDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<int?>("CourseModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("UserSection")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseModuleId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "100",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC100",
                            Email = "olusanyadavid@yahoo.com",
                            EmailConfirmed = true,
                            FullName = "Olusanya David Victor",
                            LockoutEnabled = false,
                            NormalizedEmail = "OLUSANYADAVID@YAHOO.COM",
                            NormalizedUserName = "OLUSANYADAVID@YAHOO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEiBlnC2o10DPLLcwfhSeU1PT8/l329z89a3053Cta/Npao2gegcazS8bHBW9N8Lvw==",
                            PhoneNumber = "0807212372",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STAMP100",
                            TwoFactorEnabled = false,
                            UserName = "Olusanyadavid@yahoo.com"
                        },
                        new
                        {
                            Id = "101",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC101",
                            Email = "Admin@school.com",
                            EmailConfirmed = true,
                            FullName = " ADMIN",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SCHOOL.COM",
                            NormalizedUserName = "ADMIN@SCHOOL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMZsx7GSPeVrdB029TVlDC+Y16ld17nfREgsUbSxpEc/PfClSwF3d1cYlJuIZrXpxQ==",
                            PhoneNumber = "0812329221",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STAMP101",
                            TwoFactorEnabled = false,
                            UserName = "Admin@school.com"
                        },
                        new
                        {
                            Id = "102",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC102",
                            Email = "Teacher@school.com",
                            EmailConfirmed = true,
                            FullName = "Teacher",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEACHER@SCHOOL.COM",
                            NormalizedUserName = "TEACHER@SCHOOL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOvIkJ5fcM3TG/2BY96Sr470Upk9P12X+5f+NFWsys6zI1qfjHRzTQ18VvXHaqmM4w==",
                            PhoneNumber = "09120292232",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STAMP102",
                            TwoFactorEnabled = false,
                            UserName = "Teacher@school.com"
                        },
                        new
                        {
                            Id = "106",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC0107",
                            Email = "emmanuelestheroluwasheyi17.com",
                            EmailConfirmed = true,
                            FullName = "Esther OluwaSheyi",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMMANUELESTHEROLUWASHEYI17.COM",
                            NormalizedUserName = "ESTHER OLUWASHEYI",
                            PasswordHash = "AQAAAAIAAYagAAAAEBJbD1RSIFOOPPr6mhFvVS2/+LxoEDDH13kwYSx64y4FHetpG8kOc1avuNttsz/d3w==",
                            PhoneNumber = "09120292232",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STAMP0107",
                            TwoFactorEnabled = false,
                            UserName = "Sheyi"
                        },
                        new
                        {
                            Id = "105",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC0109",
                            Email = "godwinlevel139@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Godwin Hyacinth",
                            LockoutEnabled = false,
                            NormalizedEmail = "GODWINLEVELL139@GMAIL.COM",
                            NormalizedUserName = "GODWIN HYACINTH",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ6UeBjfDsuNVpMPGFIXW+3slQqCHEJWloHrBUDeDerdiSokBp7qwLUHPArKlfTiLQ==",
                            PhoneNumber = "09022341091",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STAMP0109",
                            TwoFactorEnabled = false,
                            UserName = "HighLevel"
                        },
                        new
                        {
                            Id = "103",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC0180",
                            Email = "Student@school.com",
                            EmailConfirmed = true,
                            FullName = "Student User",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT@SCHOOL.COM",
                            NormalizedUserName = "STUDENT@SCHOOL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEgprmmn8OOOmUCevefyW1M/AtxAdkltSxSvMe4ytk4nkQVaHT3zk6ebPt84zlEPiA==",
                            PhoneNumber = "01290322332",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STAMP0108",
                            TwoFactorEnabled = false,
                            UserName = "Student@school.com"
                        },
                        new
                        {
                            Id = "104",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC104",
                            Email = "Parent@school.com",
                            EmailConfirmed = true,
                            FullName = "Parent User",
                            LockoutEnabled = false,
                            NormalizedEmail = "PARENT@SCHOOL.COM",
                            NormalizedUserName = "PARENT@SCHOOL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENaoyk+DlgQHuFPuL/BRmoOmvyagbkQcPdrOL/HcOd6dPhJJ5SdlBjqWcv8pFB/Nlg==",
                            PhoneNumber = "0810000000",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STAMP104",
                            TwoFactorEnabled = false,
                            UserName = "Parent@school.com"
                        });
                });

            modelBuilder.Entity("CourseModule", b =>
                {
                    b.HasOne("MiniSchoolSystem.Models.Course", "Course")
                        .WithMany("CourseModules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSchoolSystem.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MiniSchoolSystem.Models.UserDb", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MiniSchoolSystem.Models.UserDb", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSchoolSystem.Models.UserDb", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MiniSchoolSystem.Models.UserDb", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.Course", b =>
                {
                    b.HasOne("MiniSchoolSystem.Models.UserDb", "UserDb")
                        .WithMany()
                        .HasForeignKey("CourseUserbID");

                    b.HasOne("MiniSchoolSystem.Models.Teacher", "CourseTeacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseTeacher");

                    b.Navigation("UserDb");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.Lesson", b =>
                {
                    b.HasOne("CourseModule", "CourseModule")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniSchoolSystem.Models.StudentModel", null)
                        .WithMany("Lessons")
                        .HasForeignKey("StudentModelId");

                    b.HasOne("MiniSchoolSystem.Models.UserDb", null)
                        .WithMany("Lessons")
                        .HasForeignKey("UserDbId");

                    b.Navigation("CourseModule");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.LessonContent", b =>
                {
                    b.HasOne("MiniSchoolSystem.Models.Lesson", "Lesson")
                        .WithMany("LessonContents")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MiniSchoolSystem.Models.StudentModel", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.LessonEnrollment", b =>
                {
                    b.HasOne("MiniSchoolSystem.Models.Lesson", "Lesson")
                        .WithMany("LessonEnrollments")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniSchoolSystem.Models.UserDb", "UserDb")
                        .WithMany("LessonEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MiniSchoolSystem.Models.StudentModel", null)
                        .WithMany("lessonEnrollments")
                        .HasForeignKey("StudentName");

                    b.Navigation("Lesson");

                    b.Navigation("UserDb");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.StudentCourse", b =>
                {
                    b.HasOne("MiniSchoolSystem.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSchoolSystem.Models.StudentModel", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSchoolSystem.Models.UserDb", "userDb")
                        .WithMany()
                        .HasForeignKey("UserDbID");

                    b.Navigation("Course");

                    b.Navigation("Student");

                    b.Navigation("userDb");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.StudentModel", b =>
                {
                    b.HasOne("MiniSchoolSystem.Models.UserDb", "StudentDb")
                        .WithOne("Student")
                        .HasForeignKey("MiniSchoolSystem.Models.StudentModel", "StudentId");

                    b.Navigation("StudentDb");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.Teacher", b =>
                {
                    b.HasOne("MiniSchoolSystem.Models.UserDb", "User")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.TeacherSection", b =>
                {
                    b.HasOne("MiniSchoolSystem.Models.Teacher", "Teacher")
                        .WithMany("TeacherSections")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.UserDb", b =>
                {
                    b.HasOne("CourseModule", "CourseModule")
                        .WithMany()
                        .HasForeignKey("CourseModuleId");

                    b.Navigation("CourseModule");
                });

            modelBuilder.Entity("CourseModule", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.Course", b =>
                {
                    b.Navigation("CourseModules");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.Lesson", b =>
                {
                    b.Navigation("LessonContents");

                    b.Navigation("LessonEnrollments");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.StudentModel", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("lessonEnrollments");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.Teacher", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("TeacherSections");
                });

            modelBuilder.Entity("MiniSchoolSystem.Models.UserDb", b =>
                {
                    b.Navigation("LessonEnrollments");

                    b.Navigation("Lessons");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
